"""
Dynamic Kafka Topic Router for the Simulation Egress.

This module intercepts events generated by the dynamic-des environment and routes
them to their appropriate Kafka topics based on their internal payload structure.
"""

from src.config import (
    TOPIC_GROUND_TRUTH,
    TOPIC_LIFECYCLE,
    TOPIC_PREDICTION_REQUESTS,
    TOPIC_TELEMETRY,
)


def custom_topic_router(data: dict) -> str:
    """
    Routes the dynamic-des streams to specific Kafka topics.

    This function inspects the envelope of the event emitted by the simulation engine.
    If the event is an explicit prediction or ground truth event, it routes it to the
    machine learning pipelines. Otherwise, it routes telemetry and lifecycle data
    to monitoring topics.

    Args:
        data (dict): The raw JSON payload generated by the simulation.

    Returns:
        str: The name of the target Kafka topic.
    """
    stream_type = data.get("stream_type")

    # Route real-time dashboard updates
    if stream_type == "telemetry":
        return TOPIC_TELEMETRY

    value = data.get("value", {})
    if isinstance(value, dict):
        event_type = value.get("event_type")

        # Route Event A (Pre-pass prediction)
        if event_type == "prediction_request":
            return TOPIC_PREDICTION_REQUESTS

        # Route Event B (Post-pass physical reading)
        elif event_type == "ground_truth":
            return TOPIC_GROUND_TRUTH

    # Route internal simulator state changes (queued, started, finished)
    return TOPIC_LIFECYCLE
